import { useNavigate } from 'react-router-dom'
import { ArrowLeft, Printer, TrendingUp, TrendingDown, Award, Clock, BrainCircuit } from 'lucide-react'
import {
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer
} from 'recharts'

const topIssuesData = [
  { category: 'Supervisor', count: 14 },
  { category: 'Safety', count: 11 },
  { category: 'Canteen', count: 8 },
  { category: 'Facility', count: 6 },
  { category: 'Pay', count: 4 },
]

const sectorRankings = [
  { sector: 'Warehouse', score: 3.8, trend: 'up' },
  { sector: 'Quality Control', score: 3.5, trend: 'up' },
  { sector: 'Maintenance', score: 3.2, trend: 'stable' },
  { sector: 'Assembly Line B', score: 3.1, trend: 'down' },
  { sector: 'Packaging', score: 2.8, trend: 'up' },
  { sector: 'Assembly Line A', score: 2.4, trend: 'down' },
  { sector: 'Paint Shop', score: 2.2, trend: 'down' },
  { sector: 'Welding', score: 1.9, trend: 'down' },
]

export default function MonthlyReport() {
  const navigate = useNavigate()

  const handlePrint = () => {
    window.print()
  }

  return (
    <div className="min-h-screen bg-latte-50">
      {/* Header - hidden on print */}
      <div className="bg-white border-b border-latte-100 px-5 py-4 flex items-center gap-3 sticky top-0 z-10 print:hidden">
        <button onClick={() => navigate('/owner')} className="text-latte-400 hover:text-latte-700 transition-colors">
          <ArrowLeft className="w-5 h-5" />
        </button>
        <div className="flex-1">
          <h1 className="font-semibold text-espresso">Monthly Report</h1>
          <p className="text-xs text-latte-400">AI-generated summary</p>
        </div>
        <button onClick={handlePrint} className="flex items-center gap-1.5 text-sm text-latte-600 border border-latte-200 px-3 py-1.5 rounded-xl hover:bg-latte-50 transition-colors">
          <Printer size={14} /> Print Report
        </button>
      </div>

      <div className="px-5 py-6 max-w-3xl mx-auto space-y-6">
        {/* Report header */}
        <div className="text-center py-4 border-b-2 border-latte-200">
          <h1 className="text-2xl font-bold text-espresso">EmPulse Monthly Report</h1>
          <p className="text-latte-500 text-sm mt-1">January 2024</p>
          <p className="text-latte-400 text-xs mt-0.5">Auto-generated by AI · Confidential</p>
        </div>

        {/* Summary stats */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          <SummaryCard label="Total Complaints" value="43" sub="This month" />
          <SummaryCard label="Resolved" value="28" sub="65% rate" />
          <SummaryCard label="Avg Response" value="18hr" sub="From raise to action" />
          <SummaryCard label="Flight Risk" value="3" sub="Workers at risk" />
        </div>

        {/* Top issues chart */}
        <div className="card">
          <p className="font-semibold text-espresso mb-1">Top Issues by Category</p>
          <p className="text-latte-400 text-xs mb-4">Complaint count by type</p>
          <ResponsiveContainer width="100%" height={200}>
            <BarChart data={topIssuesData} layout="vertical" barSize={20}>
              <XAxis type="number" tick={{ fontSize: 11, fill: '#b08050' }} axisLine={false} tickLine={false} />
              <YAxis type="category" dataKey="category" tick={{ fontSize: 12, fill: '#6e4e2a' }} width={90} axisLine={false} tickLine={false} />
              <Tooltip contentStyle={{ background: '#fff', border: '1px solid #ead9c2', borderRadius: 8, fontSize: 12 }} />
              <Bar dataKey="count" fill="#6e4e2a" radius={[0, 6, 6, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>

        {/* Sector rankings table */}
        <div className="card">
          <p className="font-semibold text-espresso mb-4">Sector Rankings</p>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-latte-100">
                  <th className="text-left py-2 text-latte-500 font-medium">#</th>
                  <th className="text-left py-2 text-latte-500 font-medium">Sector</th>
                  <th className="text-center py-2 text-latte-500 font-medium">Health Score</th>
                  <th className="text-center py-2 text-latte-500 font-medium">Trend</th>
                </tr>
              </thead>
              <tbody>
                {sectorRankings.map((s, i) => (
                  <tr key={s.sector} className="border-b border-latte-50">
                    <td className="py-2.5 text-latte-400 font-medium">{i + 1}</td>
                    <td className="py-2.5 text-espresso font-medium">{s.sector}</td>
                    <td className="py-2.5 text-center">
                      <span className={`font-bold ${s.score >= 3.5 ? 'text-green-600' : s.score >= 2.5 ? 'text-amber-600' : 'text-red-600'}`}>
                        {s.score.toFixed(1)}
                      </span>
                    </td>
                    <td className="py-2.5 text-center">
                      {s.trend === 'up' && <TrendingUp size={16} className="text-green-500 inline" />}
                      {s.trend === 'down' && <TrendingDown size={16} className="text-red-500 inline" />}
                      {s.trend === 'stable' && <span className="text-latte-400">→</span>}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Best performer + worst response time */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div className="card bg-green-50 border-green-200">
            <div className="flex items-center gap-2 mb-2">
              <Award size={16} className="text-green-600" />
              <p className="text-sm font-semibold text-green-700">Best Performer</p>
            </div>
            <p className="text-lg font-bold text-green-800">Rajesh Kumar</p>
            <p className="text-xs text-green-600 mt-1">Assembly Line B · Score 94</p>
            <p className="text-xs text-green-600">30-day streak · 12 peer votes</p>
          </div>
          <div className="card bg-red-50 border-red-200">
            <div className="flex items-center gap-2 mb-2">
              <Clock size={16} className="text-red-600" />
              <p className="text-sm font-semibold text-red-700">Worst Response Time</p>
            </div>
            <p className="text-lg font-bold text-red-800">72 hours</p>
            <p className="text-xs text-red-600 mt-1">Welding sector · Safety complaint</p>
            <p className="text-xs text-red-600">Admin inaction led to auto-escalation</p>
          </div>
        </div>

        {/* AI Key Finding */}
        <div className="card bg-latte-50 border-latte-200">
          <div className="flex items-start gap-3">
            <BrainCircuit size={20} className="text-latte-700 shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold text-espresso mb-1">AI Key Finding</p>
              <p className="text-sm text-latte-700">
                Canteen complaints dropped <strong className="text-green-600">40%</strong> after vendor change on Jan 12. 
                Worker satisfaction in food category improved from 2.1 to 3.8 score.
              </p>
              <p className="text-xs text-latte-500 mt-2">
                This validates the intervention. Recommend similar approach for facility complaints in Welding sector.
              </p>
            </div>
          </div>
        </div>

        {/* Print button at bottom */}
        <div className="text-center pt-4 print:hidden">
          <button onClick={handlePrint} className="btn-primary inline-flex items-center gap-2">
            <Printer size={16} /> Print Report
          </button>
        </div>
      </div>
    </div>
  )
}

function SummaryCard({ label, value, sub }: { label: string; value: string; sub: string }) {
  return (
    <div className="card text-center">
      <p className="text-2xl font-bold text-latte-700">{value}</p>
      <p className="text-sm font-medium text-espresso mt-0.5">{label}</p>
      <p className="text-xs text-latte-400 mt-0.5">{sub}</p>
    </div>
  )
}
